export type Locale = 'en' | 'pt-BR'
export type Theme = 'light' | 'dark'

export const content = {
  en: {
    metaTitle: 'Rodrigo Lima — Full Stack Software Engineer & CTO',
    metaDescription:
      'Rodrigo Lima builds web products and AI workflows. Explore public projects with code, tests, and engineering decisions.',
    skip: 'Skip to content',
    backToTop: 'Rodrigo Lima, back to top',
    footerBackToTop: 'Back to top',
    navigation: 'Primary navigation',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    menuWork: 'Work',
    menuCompany: 'OpportunusAI',
    menuApproach: 'Approach',
    menuAbout: 'About',
    menuContact: 'Let’s connect',
    languageControl: 'Language',
    english: 'English',
    portuguese: 'Português do Brasil',
    themeControl: 'Theme',
    darkMode: 'Switch to dark mode',
    lightMode: 'Switch to light mode',
    dark: 'Dark',
    light: 'Light',
    heroRole: 'FULL STACK ENGINEER',
    heroAi: 'APPLIED AI',
    heroCto: 'Co-founder and CTO at OpportunusAI',
    heroTitleStart: 'From complex',
    heroTitleMiddle: 'systems to',
    heroTitleEmphasis: 'clear',
    heroTitleEnd: 'experiences',
    heroLead:
      'I’m Rodrigo Lima. I build web products and AI workflows, from the interface to the systems behind them.',
    heroAction: 'Explore my work',
    githubProfile: 'GitHub profile',
    focusAreas: 'Core focus areas',
    portraitAlt: 'Portrait of Rodrigo Lima',
    artTop: 'ENGINEERING / 001',
    artLeft: 'interface',
    artRight: 'logic',
    artNote: 'idea → system',
    workKicker: '01 / SELECTED WORK',
    workTitleStart: 'Proof in the',
    workTitleEnd: 'work.',
    workIntro: 'Three public projects, with code and tests you can inspect.',
    selectedWork: 'SELECTED WORK',
    engineeringDecision: 'HOW IT WORKS',
    technologies: 'technologies',
    repositoryAction: 'Explore repository',
    repositoryAria: (title: string) => `View ${title} source code on GitHub (opens in a new tab)`,
    workFooter: 'Each repository includes setup steps and explains what its example covers.',
    allRepositories: 'See all repositories',
    companyKicker: '02 / BUILDING OPPORTUNUSAI',
    companyTitleStart: 'From the first version',
    companyTitleEnd: 'to real operations.',
    companyIntro:
      'As Co-founder and CTO, I lead the technical evolution of OpportunusAI. The public dashboard shows V1; the private V2 is the operational platform. It brings together conversations and integrated chat, customers, orders, carts, and campaigns. The team reviews AI knowledge before publishing it.',
    companyPrivacy:
      'These are real V2 interface captures. Customer details and operational figures were removed or replaced with examples; the code stays private.',
    companySiteLink: 'Explore OpportunusAI',
    companySlideLabel: 'PRIVATE V2 / REAL UI / SANITIZED CONTENT',
    companyImageOrigin: 'REAL INTERFACE · SAFE EXCERPT',
    companySlideTitles: [
      'Conversations, together',
      'Knowledge with a review step',
      'Campaign planning',
    ],
    companySlideBodies: [
      'An integrated inbox keeps human replies and AI assistance in one workflow.',
      'The team reviews what the AI learned before that knowledge is published.',
      'A workspace for campaign drafts. This capture shows the planning interface, not a sent campaign.',
    ],
    companySlideAlt: [
      'Sanitized capture of the V2 conversation view with fictional example messages',
      'Sanitized capture of the V2 AI knowledge review view with counts hidden',
      'Sanitized capture of the V2 campaign planning form with a synthetic placeholder',
    ],
    companyCarousel: 'Sanitized interface captures of private OpportunusAI V2',
    previousSlide: 'Previous example',
    nextSlide: 'Next example',
    slideOf: (current: number, total: number) => `${current} of ${total}`,
    approachKicker: '03 / ENGINEERING APPROACH',
    approachTitleStart: 'The details make',
    approachTitleEnd: 'the difference.',
    approachIntro:
      'I think through access, failure, and what another developer will need to run and understand the code.',
    principleOneTitle: 'Define the boundary',
    principleOneBody:
      'Check identity and permissions on the server and at the data boundary, not just in the UI.',
    principleTwoTitle: 'Design for failure',
    principleTwoBody: 'Give invalid input, denied access, and unavailable context clear responses.',
    principleThreeTitle: 'Make it reproducible',
    principleThreeBody:
      'Document the setup, use fictional examples, and keep tests close to the code.',
    aboutKicker: '04 / ABOUT',
    aboutTitleStart: 'Engineering across',
    aboutTitleEnd: 'the whole system.',
    aboutOne:
      'I work across product interfaces, backend APIs, automation, and system architecture.',
    aboutTwo:
      'I focus on JavaScript, Python, LangChain, LangGraph, and n8n. I also work with Docker Swarm and Zero Trust access controls. The public projects show verifiable parts of that work.',
    practiceAreas: 'Areas of practice',
    practiceWeb: 'Web applications',
    practiceAi: 'Applied AI',
    practiceAutomation: 'Automation',
    practiceArchitecture: 'System architecture',
    summaryLabel: 'IN BRIEF',
    summaryAria: 'Profile summary',
    summary:
      'I’m a full stack software engineer and Co-founder & CTO at OpportunusAI. I use JavaScript, Python, system architecture, and applied AI to build useful products with code you can inspect.',
    contactKicker: '05 / CONTACT',
    contactTitleStart: 'Let’s build something',
    contactTitleEnd: 'worth using.',
    contactIntro:
      'Want to talk about product, engineering, or applied AI? Explore the code or reach out on LinkedIn.',
    linkedinAction: 'Connect on LinkedIn',
    githubAction: 'View GitHub',
    footerRole: 'Full Stack Software Engineer · Co-founder & CTO',
  },
  'pt-BR': {
    metaTitle: 'Rodrigo Lima — Engenheiro de Software Full Stack e CTO',
    metaDescription:
      'Rodrigo Lima desenvolve produtos web, IA aplicada e automações com limites claros de engenharia. Conheça código público e decisões técnicas.',
    skip: 'Ir para o conteúdo',
    backToTop: 'Rodrigo Lima, voltar ao topo',
    footerBackToTop: 'Voltar ao topo',
    navigation: 'Navegação principal',
    openMenu: 'Abrir navegação',
    closeMenu: 'Fechar navegação',
    menuWork: 'Projetos',
    menuCompany: 'OpportunusAI',
    menuApproach: 'Abordagem',
    menuAbout: 'Sobre',
    menuContact: 'Vamos conversar',
    languageControl: 'Idioma',
    english: 'Inglês',
    portuguese: 'Português do Brasil',
    themeControl: 'Tema',
    darkMode: 'Ativar modo escuro',
    lightMode: 'Ativar modo claro',
    dark: 'Escuro',
    light: 'Claro',
    heroRole: 'ENGENHEIRO FULL STACK',
    heroAi: 'IA APLICADA',
    heroCto: 'Cofundador e CTO da OpportunusAI',
    heroTitleStart: 'Do problema',
    heroTitleMiddle: 'complexo ao',
    heroTitleEmphasis: 'produto',
    heroTitleEnd: 'claro',
    heroLead:
      'Sou Rodrigo Lima. Crio produtos digitais e automações com IA, unindo arquitetura, boas interfaces e código testável.',
    heroAction: 'Conheça meus projetos',
    githubProfile: 'Perfil no GitHub',
    focusAreas: 'Áreas principais',
    portraitAlt: 'Retrato de Rodrigo Lima',
    artTop: 'ENGENHARIA / 001',
    artLeft: 'interface',
    artRight: 'lógica',
    artNote: 'ideia → sistema',
    workKicker: '01 / PROJETOS SELECIONADOS',
    workTitleStart: 'Projetos que mostram',
    workTitleEnd: 'meu trabalho.',
    workIntro:
      'Três projetos públicos, com código, testes e escolhas técnicas que você pode conferir.',
    selectedWork: 'PROJETOS SELECIONADOS',
    engineeringDecision: 'COMO FUNCIONA',
    technologies: 'tecnologias',
    repositoryAction: 'Explorar repositório',
    repositoryAria: (title: string) =>
      `Ver o código-fonte de ${title} no GitHub (abre em nova aba)`,
    workFooter:
      'Nos repositórios, você encontra como executar cada projeto, os testes e o que cada exemplo cobre.',
    allRepositories: 'Ver todos os repositórios',
    companyKicker: '02 / CONSTRUINDO A OPPORTUNUSAI',
    companyTitleStart: 'Da primeira versão',
    companyTitleEnd: 'à operação real.',
    companyIntro:
      'Como cofundador e CTO, lidero a evolução técnica da OpportunusAI. O dashboard público mostra a V1; a V2 é a plataforma privada em operação. Ela reúne conversas, clientes, pedidos, carrinhos e campanhas. O conhecimento da IA passa por revisão da equipe antes de ser publicado.',
    companyPrivacy:
      'Os recortes mostram a interface real da V2. Dados de clientes e números da operação foram removidos ou trocados por exemplos; o código segue privado.',
    companySiteLink: 'Conhecer a OpportunusAI',
    companySlideLabel: 'V2 PRIVADA / INTERFACE REAL / CONTEÚDO SANITIZADO',
    companyImageOrigin: 'INTERFACE REAL · RECORTE SEGURO',
    companySlideTitles: [
      'Conversas no mesmo fluxo',
      'Aprendizado com revisão',
      'Planejamento de campanhas',
    ],
    companySlideBodies: [
      'Chat, histórico e apoio da IA no mesmo atendimento.',
      'A equipe revisa o que a IA aprendeu antes de publicar.',
      'Um espaço para preparar rascunhos. O recorte mostra a tela de planejamento, não uma campanha enviada.',
    ],
    companySlideAlt: [
      'Captura sanitizada de uma conversa na V2 com mensagens de exemplo',
      'Captura sanitizada da revisão do aprendizado da IA na V2, com contagens ocultas',
      'Captura sanitizada do planejamento de campanhas da V2, com texto de exemplo',
    ],
    companyCarousel: 'Recortes sanitizados da interface privada da OpportunusAI V2',
    previousSlide: 'Exemplo anterior',
    nextSlide: 'Próximo exemplo',
    slideOf: (current: number, total: number) => `${current} de ${total}`,
    approachKicker: '03 / ABORDAGEM DE ENGENHARIA',
    approachTitleStart: 'O cuidado está',
    approachTitleEnd: 'nos detalhes.',
    approachIntro:
      'Penso também no que dá errado: acessos negados, fluxos interrompidos e decisões que outra pessoa precisará entender.',
    principleOneTitle: 'Acesso bem definido',
    principleOneBody:
      'Identidade e permissões precisam ser verificadas no servidor e nos dados, além da interface.',
    principleTwoTitle: 'Falhas previstas',
    principleTwoBody:
      'Entradas inválidas, acesso negado e contexto indisponível têm respostas claras e testáveis.',
    principleThreeTitle: 'Fácil de reproduzir',
    principleThreeBody:
      'Documentação, exemplos fictícios e testes ajudam outra pessoa a entender e executar o projeto.',
    aboutKicker: '04 / SOBRE',
    aboutTitleStart: 'Do produto',
    aboutTitleEnd: 'à infraestrutura.',
    aboutOne:
      'Trabalho do frontend ao backend, da experiência de uso à arquitetura que mantém o produto confiável.',
    aboutTwo:
      'Hoje meu foco é JavaScript, Python, LangChain, LangGraph e n8n. Também atuo com Docker Swarm e controles de acesso Zero Trust. Os projetos públicos mostram partes verificáveis desse trabalho.',
    practiceAreas: 'Áreas de atuação',
    practiceWeb: 'Aplicações web',
    practiceAi: 'IA aplicada',
    practiceAutomation: 'Automação',
    practiceArchitecture: 'Arquitetura de sistemas',
    summaryLabel: 'EM RESUMO',
    summaryAria: 'Resumo profissional',
    summary:
      'Sou engenheiro de software full stack e cofundador e CTO da OpportunusAI. Trabalho com JavaScript, Python, arquitetura de sistemas e IA aplicada para transformar problemas complexos em produtos úteis e verificáveis.',
    contactKicker: '05 / CONTATO',
    contactTitleStart: 'Vamos criar algo',
    contactTitleEnd: 'que valha usar.',
    contactIntro:
      'Quer conversar sobre produto, engenharia ou IA aplicada? Veja o código ou fale comigo pelo LinkedIn.',
    linkedinAction: 'Conectar no LinkedIn',
    githubAction: 'Ver GitHub',
    footerRole: 'Engenheiro de Software Full Stack · Cofundador e CTO',
  },
} as const
