export type Locale = 'en' | 'pt-BR'
export type Theme = 'light' | 'dark'

export const content = {
  en: {
    metaTitle: 'Rodrigo Lima — Full Stack Software Engineer & CTO',
    metaDescription:
      'Rodrigo Lima is a full stack software engineer and OpportunusAI co-founder and CTO. Explore web applications, applied AI, and public projects with code and tests.',
    skip: 'Skip to content',
    backToTop: 'Rodrigo Lima, back to top',
    footerBackToTop: 'Back to top',
    navigation: 'Primary navigation',
    openMenu: 'Open navigation',
    closeMenu: 'Close navigation',
    menuWork: 'Work',
    menuCompany: 'OpportunusAI',
    menuApproach: 'Approach',
    menuAbout: 'About',
    menuContact: 'Let’s connect',
    languageControl: 'Language',
    english: 'English',
    portuguese: 'Português do Brasil',
    themeControl: 'Theme',
    darkMode: 'Switch to dark mode',
    lightMode: 'Switch to light mode',
    dark: 'Dark',
    light: 'Light',
    heroRole: 'FULL STACK SOFTWARE ENGINEER',
    heroAi: 'APPLIED AI',
    heroCto: 'Co-founder and CTO at OpportunusAI',
    heroTitleStart: 'From code',
    heroTitleEmphasis: 'to production',
    heroLead:
      'I’m a full stack software engineer focused on applied AI. I build scalable software, from architecture to production.',
    heroAction: 'Explore my work',
    githubProfile: 'GitHub profile',
    focusAreas: 'Core focus areas',
    portraitAlt: 'Portrait of Rodrigo Lima',
    artTop: 'ENGINEERING / 001',
    artLeft: 'interface',
    artRight: 'logic',
    artNote: 'idea → system',
    workKicker: '01 / SELECTED WORK',
    workTitleStart: 'See how I',
    workTitleEnd: 'build.',
    workIntro:
      'From a full stack dashboard to LangGraph and n8n workflows: public code you can inspect, run, and test.',
    selectedWork: 'SELECTED WORK',
    engineeringDecision: 'HOW IT WORKS',
    technologies: 'technologies',
    repositoryAction: 'Explore repository',
    repositoryAria: (title: string) => `View ${title} source code on GitHub (opens in a new tab)`,
    workFooter: 'Code, tests, and setup steps are in each repository.',
    allRepositories: 'See all repositories',
    companyKicker: '02 / BUILDING OPPORTUNUSAI',
    companyTitleStart: 'From public V1',
    companyTitleEnd: 'to a private V2 in use.',
    companyIntro:
      'As Co-founder and CTO, I lead product engineering at OpportunusAI. V2 brings analytics, AI-assisted conversations, knowledge review, and campaigns into one product.',
    companyPrivacy:
      'These V2 screens use fictional content and figures. Product code and production data remain private.',
    companySiteLink: 'Explore OpportunusAI',
    companyViewImage: 'View full image',
    companySlideLabel: 'PRIVATE V2 · DEMO DATA',
    companySlideTitles: [
      'Operations overview',
      'AI assistance with human control',
      'Knowledge reviewed by the team',
    ],
    companySlideBodies: [
      'Sales, conversations needing attention, and AI activity in one place.',
      'The team can reply, request a suggestion, or pause AI in the same conversation.',
      'The team can review suggested knowledge before using it in future replies.',
    ],
    companySlideAlt: [
      'V2 overview interface with navigation, sales chart, and synthetic demo figures',
      'V2 conversation interface with fictional messages and AI controls',
      'V2 AI knowledge review interface with synthetic examples',
    ],
    companyCarousel: 'Sanitized interface captures of private OpportunusAI V2',
    previousSlide: 'Previous example',
    nextSlide: 'Next example',
    slideOf: (current: number, total: number) => `${current} of ${total}`,
    approachKicker: '03 / ENGINEERING APPROACH',
    approachTitleStart: 'What the code',
    approachTitleEnd: 'must guarantee.',
    approachIntro:
      'I design for denied access, missing context, and the person who maintains the system next. Those choices are visible in the code and tests.',
    principleOneTitle: 'Access boundaries',
    principleOneBody: 'I define where each permission is enforced and test the denied paths.',
    principleTwoTitle: 'Predictable failures',
    principleTwoBody: 'Invalid input and unavailable context lead to controlled responses.',
    principleThreeTitle: 'Reproducible work',
    principleThreeBody:
      'Fictional data, setup steps, and tests let another developer run the project.',
    aboutKicker: '04 / ABOUT',
    aboutTitleStart: 'Engineering across',
    aboutTitleEnd: 'the whole system.',
    aboutOne:
      'I work across interfaces, APIs, automations, and architecture. I make those parts work together for the people using the product.',
    aboutTwo:
      'My current focus is JavaScript/TypeScript and Python, with LangChain, LangGraph, and n8n for applied AI and automation.',
    aboutInfraTitle: 'Infrastructure & security',
    aboutInfraOperations:
      'I work with production infrastructure, including high-availability, multi-manager Docker Swarm clusters, Traefik, Prometheus/Grafana observability, health checks, and watchdogs.',
    aboutInfraSecurity:
      'I also use Cloudflare Tunnel and Access, Zero Trust controls, and rate limiting to manage access and protect traffic.',
    practiceAreas: 'Areas of practice',
    practiceWeb: 'Web applications',
    practiceAi: 'Applied AI',
    practiceAutomation: 'Automation',
    practiceArchitecture: 'System architecture',
    contactKicker: '05 / CONTACT',
    contactTitleStart: 'Have an engineering challenge?',
    contactTitleEnd: 'Let’s talk.',
    contactIntro:
      'I’m open to software engineering roles and projects across full stack development, architecture, and applied AI. Explore my work on GitHub and connect on LinkedIn.',
    linkedinAction: 'Connect on LinkedIn',
    githubAction: 'View code on GitHub',
    footerRole: 'Full Stack Software Engineer · Co-founder & CTO',
  },
  'pt-BR': {
    metaTitle: 'Rodrigo Lima — Engenheiro de Software Full Stack e CTO',
    metaDescription:
      'Rodrigo Lima é engenheiro de software full stack, cofundador e CTO da OpportunusAI. Conheça aplicações web, IA aplicada e projetos públicos com código e testes.',
    skip: 'Ir para o conteúdo',
    backToTop: 'Rodrigo Lima, voltar ao topo',
    footerBackToTop: 'Voltar ao topo',
    navigation: 'Navegação principal',
    openMenu: 'Abrir navegação',
    closeMenu: 'Fechar navegação',
    menuWork: 'Projetos',
    menuCompany: 'OpportunusAI',
    menuApproach: 'Abordagem',
    menuAbout: 'Sobre',
    menuContact: 'Vamos conversar',
    languageControl: 'Idioma',
    english: 'Inglês',
    portuguese: 'Português do Brasil',
    themeControl: 'Tema',
    darkMode: 'Ativar modo escuro',
    lightMode: 'Ativar modo claro',
    dark: 'Escuro',
    light: 'Claro',
    heroRole: 'ENGENHEIRO DE SOFTWARE FULL STACK',
    heroAi: 'IA APLICADA',
    heroCto: 'Cofundador e CTO da OpportunusAI',
    heroTitleStart: 'Do código',
    heroTitleEmphasis: 'à operação',
    heroLead:
      'Sou engenheiro de software full stack com foco em IA aplicada. Desenvolvo soluções escaláveis, da arquitetura à produção.',
    heroAction: 'Conheça meus projetos',
    githubProfile: 'Perfil no GitHub',
    focusAreas: 'Áreas principais',
    portraitAlt: 'Retrato de Rodrigo Lima',
    artTop: 'ENGENHARIA / 001',
    artLeft: 'interface',
    artRight: 'lógica',
    artNote: 'ideia → sistema',
    workKicker: '01 / PROJETOS SELECIONADOS',
    workTitleStart: 'Veja como eu',
    workTitleEnd: 'construo.',
    workIntro:
      'Do dashboard full stack aos fluxos com LangGraph e n8n: código público para examinar, executar e testar.',
    selectedWork: 'PROJETOS SELECIONADOS',
    engineeringDecision: 'COMO FUNCIONA',
    technologies: 'tecnologias',
    repositoryAction: 'Explorar repositório',
    repositoryAria: (title: string) =>
      `Ver o código-fonte de ${title} no GitHub (abre em nova aba)`,
    workFooter: 'Código, testes e instruções de execução em cada repositório.',
    allRepositories: 'Ver todos os repositórios',
    companyKicker: '02 / CONSTRUINDO A OPPORTUNUSAI',
    companyTitleStart: 'Da V1 pública',
    companyTitleEnd: 'à V2 em operação.',
    companyIntro:
      'Como cofundador e CTO, lidero a engenharia de produto da OpportunusAI. A V2 reúne indicadores, atendimento com IA, revisão do conhecimento e campanhas em um só produto.',
    companyPrivacy:
      'Estas telas da V2 usam conteúdo e números fictícios. Código e dados de produção seguem privados.',
    companySiteLink: 'Conhecer a OpportunusAI',
    companyViewImage: 'Ampliar imagem',
    companySlideLabel: 'V2 PRIVADA · DADOS FICTÍCIOS',
    companySlideTitles: [
      'Visão da operação',
      'IA com controle humano',
      'Aprendizado revisado pela equipe',
    ],
    companySlideBodies: [
      'Vendas, conversas que pedem atenção e atuação da IA em um só lugar.',
      'A equipe responde, pede sugestões ou pausa a IA na mesma conversa.',
      'A equipe pode revisar conhecimentos sugeridos antes de usá-los em novas respostas.',
    ],
    companySlideAlt: [
      'Interface da visão geral da V2 com navegação, gráfico e valores fictícios',
      'Interface de conversa da V2 com mensagens fictícias e controles da IA',
      'Interface de revisão do conhecimento da IA na V2 com exemplos fictícios',
    ],
    companyCarousel: 'Recortes sanitizados da interface privada da OpportunusAI V2',
    previousSlide: 'Exemplo anterior',
    nextSlide: 'Próximo exemplo',
    slideOf: (current: number, total: number) => `${current} de ${total}`,
    approachKicker: '03 / ABORDAGEM DE ENGENHARIA',
    approachTitleStart: 'O que o código',
    approachTitleEnd: 'precisa garantir.',
    approachIntro:
      'Penso no que acontece quando o acesso é negado, falta contexto ou outra pessoa precisa manter o sistema. Isso aparece no código e nos testes.',
    principleOneTitle: 'Limites de acesso',
    principleOneBody:
      'Defino onde cada permissão é verificada e testo os caminhos de acesso negado.',
    principleTwoTitle: 'Falhas previsíveis',
    principleTwoBody: 'Entradas inválidas e contexto indisponível levam a respostas controladas.',
    principleThreeTitle: 'Execução reproduzível',
    principleThreeBody:
      'Dados fictícios, instruções e testes permitem que outra pessoa rode o projeto.',
    aboutKicker: '04 / SOBRE',
    aboutTitleStart: 'Do produto',
    aboutTitleEnd: 'à infraestrutura.',
    aboutOne:
      'Trabalho em interfaces, APIs, automações e arquitetura. Faço essas partes funcionarem juntas para quem usa o produto.',
    aboutTwo:
      'Meu foco hoje é JavaScript/TypeScript e Python, com LangChain, LangGraph e n8n em IA aplicada e automação.',
    aboutInfraTitle: 'Infraestrutura e segurança',
    aboutInfraOperations:
      'Trabalho com infraestrutura de produção, incluindo clusters Docker Swarm com múltiplos managers e alta disponibilidade, além de Traefik, observabilidade com Prometheus/Grafana, health checks e watchdogs.',
    aboutInfraSecurity:
      'Também uso Cloudflare Tunnel/Access, controles Zero Trust e rate limiting para gerenciar acessos e proteger o tráfego.',
    practiceAreas: 'Áreas de atuação',
    practiceWeb: 'Aplicações web',
    practiceAi: 'IA aplicada',
    practiceAutomation: 'Automação',
    practiceArchitecture: 'Arquitetura de sistemas',
    contactKicker: '05 / CONTATO',
    contactTitleStart: 'Tem um desafio técnico?',
    contactTitleEnd: 'Vamos conversar.',
    contactIntro:
      'Estou aberto a oportunidades em engenharia full stack, arquitetura e IA aplicada. Veja meus projetos no GitHub e fale comigo pelo LinkedIn.',
    linkedinAction: 'Conectar no LinkedIn',
    githubAction: 'Ver código no GitHub',
    footerRole: 'Engenheiro de Software Full Stack · Cofundador e CTO',
  },
} as const
